# Generated by Django 4.1.3 on 2022-11-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="full name"
            ),
        ),
    ]
