# Generated by Django 4.1.4 on 2022-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_night_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="bid_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="BID ID"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="dwellent_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dwellent ID"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="non_seamless",
            field=models.BooleanField(
                default=False, verbose_name="Non Seamless Contract"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="property_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Property Reference"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="seamless",
            field=models.BooleanField(default=False, verbose_name="Seamless Contract"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="bid_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="BID ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="dwellent_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dwellent ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="non_seamless",
            field=models.BooleanField(
                default=False, verbose_name="Non Seamless Contract"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="property_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Property Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="seamless",
            field=models.BooleanField(default=False, verbose_name="Seamless Contract"),
        ),
    ]
