# Generated by Django 4.1.4 on 2022-12-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_account_manager_alter_client_client_and_more"),
        ("utilities", "0001_initial"),
        ("contracts", "0004_alter_contract_bid_id_alter_contract_dwellent_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="billing_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Billing Address"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="building_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Building Name"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="Business Name"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_contracts",
                to="clients.client",
                verbose_name="Client Name",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="company_reg_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Company Reg Number"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="mpan_mpr",
            field=models.CharField(max_length=255, verbose_name="MPAN/MPR"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="portal_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Portal Status"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="site_address",
            field=models.TextField(verbose_name="Site Address"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_suppliers",
                to="utilities.supplier",
                verbose_name="Supplier Name",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="top_line",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Top Line"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="utility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_utilities",
                to="utilities.utility",
                verbose_name="Utility Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="billing_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Billing Address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="building_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Building Name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="Business Name"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
                verbose_name="Client Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="company_reg_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Company Reg Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="mpan_mpr",
            field=models.CharField(max_length=255, verbose_name="MPAN/MPR"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="portal_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Portal Status"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="site_address",
            field=models.TextField(verbose_name="Site Address"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilities.supplier",
                verbose_name="Supplier Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="top_line",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Top Line"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="utility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilities.utility",
                verbose_name="Utility Type",
            ),
        ),
    ]
