# Generated by Django 4.1.4 on 2022-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Account Number"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract End Date"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="day_consumption",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Day Consumption"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="eac",
            field=models.FloatField(blank=True, null=True, verbose_name="EAC"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="night_consumption",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Night Consumption"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="vat",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="VAT"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Account Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract End Date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="day_consumption",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Day Consumption"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="eac",
            field=models.FloatField(blank=True, null=True, verbose_name="EAC"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="night_consumption",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Night Consumption"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="vat",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="VAT"
            ),
        ),
    ]
