# Generated by Django 4.1.4 on 2023-01-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_annualised_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['client'], 'verbose_name': 'Client Contract', 'verbose_name_plural': 'Client Contracts'},
        ),
    ]
