# Generated by Django 4.1.4 on 2022-12-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('site_address', models.TextField()),
                ('mpan_mpr', models.CharField(max_length=255)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('objection_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.CharField(blank=True, max_length=25, null=True)),
                ('eac', models.CharField(blank=True, max_length=35, null=True)),
                ('is_directors_approval', models.BooleanField(default=False)),
                ('objection_status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_objections', to='clients.client')),
                ('new_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_suppliers', to='utilities.supplier')),
                ('objecting_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objecting_suppliers', to='utilities.supplier')),
            ],
            options={
                'verbose_name': 'Contract Objection',
                'verbose_name_plural': 'Contract Objections',
            },
        ),
        migrations.CreateModel(
            name='HistoricalObjection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('site_address', models.TextField()),
                ('mpan_mpr', models.CharField(max_length=255)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('objection_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.CharField(blank=True, max_length=25, null=True)),
                ('eac', models.CharField(blank=True, max_length=35, null=True)),
                ('is_directors_approval', models.BooleanField(default=False)),
                ('objection_status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utilities.supplier')),
                ('objecting_supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utilities.supplier')),
            ],
            options={
                'verbose_name': 'historical Contract Objection',
                'verbose_name_plural': 'historical Contract Objections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['mpan_mpr'], name='objections__mpan_mp_b66b48_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['client'], name='objections__client__36c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['-client'], name='objections__client__705100_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['business_name'], name='objections__busines_062c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['-business_name'], name='objections__busines_021d24_idx'),
        ),
        migrations.AddConstraint(
            model_name='objection',
            constraint=models.UniqueConstraint(fields=('mpan_mpr', 'id'), name='unique_objection'),
        ),
    ]
