# Generated by Django 4.1.4 on 2022-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjection',
            name='eac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objection',
            name='eac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
