# Generated by Django 4.1.4 on 2022-12-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_account_manager_alter_client_client_and_more'),
        ('utilities', '0001_initial'),
        ('objections', '0002_alter_historicalobjection_eac_alter_objection_eac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjection',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='business_name',
            field=models.CharField(max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Deadline Date'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='eac',
            field=models.IntegerField(blank=True, null=True, verbose_name='EAC'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='is_directors_approval',
            field=models.BooleanField(default=False, verbose_name='Directors Approval'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='mpan_mpr',
            field=models.CharField(max_length=255, verbose_name='MPAN/MPR'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='new_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utilities.supplier', verbose_name='New Supplier'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='objecting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utilities.supplier', verbose_name='Objecting Supplier'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='objection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Objection Date'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='objection_status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12, verbose_name='Objection Status'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='historicalobjection',
            name='site_address',
            field=models.TextField(verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='business_name',
            field=models.CharField(max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_objections', to='clients.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Deadline Date'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='eac',
            field=models.IntegerField(blank=True, null=True, verbose_name='EAC'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='is_directors_approval',
            field=models.BooleanField(default=False, verbose_name='Directors Approval'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='mpan_mpr',
            field=models.CharField(max_length=255, verbose_name='MPAN/MPR'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='new_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_suppliers', to='utilities.supplier', verbose_name='New Supplier'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='objecting_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objecting_suppliers', to='utilities.supplier', verbose_name='Objecting Supplier'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='objection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Objection Date'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='objection_status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12, verbose_name='Objection Status'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='site_address',
            field=models.TextField(verbose_name='Site Address'),
        ),
    ]
