# Generated by Django 4.1.4 on 2023-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0003_alter_historicalobjection_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjection',
            name='objection_status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='OUTSTANDING', max_length=12, verbose_name='Objection Status'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='objection_status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='OUTSTANDING', max_length=12, verbose_name='Objection Status'),
        ),
    ]
